/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import domain.SystemClass;

/**
 *
 * @author bacosta
 */
public class AddPostulant extends javax.swing.JFrame {

    private SystemClass system;
    /**
     * Creates new form AddPostulant
     */
    public AddPostulant(SystemClass sys ) {
        system = sys;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jobModalityGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jobModalityH = new javax.swing.JRadioButton();
        jobModalityR = new javax.swing.JRadioButton();
        jobModalityP = new javax.swing.JRadioButton();
        go = new javax.swing.JButton();
        back = new javax.swing.JButton();
        name = new javax.swing.JTextField();
        linkedin = new javax.swing.JTextField();
        mail = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        document = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Entrevistas");
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setText("Alta postulante");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(150, 10, 103, 30);

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel2.setText("Teléfono:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 220, 70, 17);

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel3.setText("Nombre:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 70, 60, 17);

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel4.setText("Cédula:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 120, 47, 17);

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel5.setText("Formato:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 370, 70, 17);

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel6.setText("Dirección:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 170, 70, 17);

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel7.setText("Mail:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 270, 50, 17);

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel8.setText("Linkedin:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 320, 70, 17);

        jobModalityGroup.add(jobModalityH);
        jobModalityH.setText("Hybrido");
        jobModalityH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jobModalityHActionPerformed(evt);
            }
        });
        jPanel1.add(jobModalityH);
        jobModalityH.setBounds(310, 370, 90, 21);

        jobModalityGroup.add(jobModalityR);
        jobModalityR.setText("Remoto");
        jobModalityR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jobModalityRActionPerformed(evt);
            }
        });
        jPanel1.add(jobModalityR);
        jobModalityR.setBounds(100, 370, 70, 21);

        jobModalityGroup.add(jobModalityP);
        jobModalityP.setText("Presencial");
        jobModalityP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jobModalityPActionPerformed(evt);
            }
        });
        jPanel1.add(jobModalityP);
        jobModalityP.setBounds(200, 370, 90, 21);

        go.setText("Siguiente");
        jPanel1.add(go);
        go.setBounds(308, 440, 90, 23);

        back.setText("Cancelar");
        jPanel1.add(back);
        back.setBounds(20, 440, 90, 23);
        jPanel1.add(name);
        name.setBounds(100, 70, 280, 23);
        jPanel1.add(linkedin);
        linkedin.setBounds(100, 320, 280, 23);
        jPanel1.add(mail);
        mail.setBounds(100, 270, 280, 23);
        jPanel1.add(phone);
        phone.setBounds(100, 220, 280, 23);
        jPanel1.add(address);
        address.setBounds(100, 170, 280, 23);
        jPanel1.add(document);
        document.setBounds(100, 120, 280, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-2, 4, 430, 490);

        setSize(new java.awt.Dimension(431, 521));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jobModalityHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jobModalityHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jobModalityHActionPerformed

    private void jobModalityRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jobModalityRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jobModalityRActionPerformed

    private void jobModalityPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jobModalityPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jobModalityPActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JButton back;
    private javax.swing.JTextField document;
    private javax.swing.JButton go;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.ButtonGroup jobModalityGroup;
    private javax.swing.JRadioButton jobModalityH;
    private javax.swing.JRadioButton jobModalityP;
    private javax.swing.JRadioButton jobModalityR;
    private javax.swing.JTextField linkedin;
    private javax.swing.JTextField mail;
    private javax.swing.JTextField name;
    private javax.swing.JTextField phone;
    // End of variables declaration//GEN-END:variables
}
