/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import domain.SystemClass;

/**
 *
 * @author bacosta
 */
public class AddPostulantSkills extends javax.swing.JFrame {
    private SystemClass system;
    /**
     * Creates new form AddPostulantSkills
     */
    public AddPostulantSkills(SystemClass sys) {
        system=sys;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        topic = new javax.swing.JComboBox<>();
        jSpinner1 = new javax.swing.JSpinner();
        remove = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        back = new javax.swing.JButton();
        go = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Entrevistas");
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setText("Alta postulante");
        jLabel1.setBounds(new java.awt.Rectangle(150, 10, 103, 30));
        jLabel1.setLocation(new java.awt.Point(150, 10));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(160, 40, 103, 18);

        jLabel2.setText("Tema:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 70, 36, 17);

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel3.setText("Experiencia:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 160, 74, 20);

        jPanel1.add(topic);
        topic.setBounds(140, 70, 260, 23);

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        jPanel1.add(jSpinner1);
        jSpinner1.setBounds(140, 100, 120, 23);

        remove.setText("Eliminar");
        jPanel1.add(remove);
        remove.setBounds(30, 210, 90, 23);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(30, 140, 370, 20);

        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(140, 160, 260, 80);

        jLabel4.setText("Nivel:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 100, 33, 20);

        add.setText("Agregar");
        jPanel1.add(add);
        add.setBounds(290, 100, 110, 23);

        back.setText("Cancelar");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back);
        back.setBounds(30, 290, 110, 23);

        go.setText("Registrar");
        go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goActionPerformed(evt);
            }
        });
        jPanel1.add(go);
        go.setBounds(290, 290, 110, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 430, 330);

        setSize(new java.awt.Dimension(431, 362));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void goActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_goActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton back;
    private javax.swing.JButton go;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JButton remove;
    private javax.swing.JComboBox<String> topic;
    // End of variables declaration//GEN-END:variables
}
