//Mateo Seijo 309095
//Bruno Acosta 313080
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import domain.Postulant;
import domain.SystemClass;
import domain.Topic;
import java.awt.Component;
import java.util.ArrayList;
import java.util.Map;
import java.util.Observable;
import java.util.Observer;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListCellRenderer;
import javax.swing.SwingUtilities;

/**
 *
 * @author bacosta
 */
public class AddPostulantSkills extends javax.swing.JFrame implements Observer {

    private SystemClass system;
    private JFrame predecesor;
    private Postulant postulant;

    DefaultListModel model = new DefaultListModel();

    /**
     * Creates new form AddPostulantSkills
     */
    public AddPostulantSkills(SystemClass sys, JFrame pre, Postulant postulant) {
        predecesor = pre;
        system = sys;
        this.postulant = postulant;
        sys.addObserver(this);
        initComponents();
        listSkills.setModel(model);
        setTopicCombo();
        setListItem();
        postulantData.setText(this.postulant.toString());
    }

    public void update(Observable o, Object ob) {

        setTopicCombo();
        setListItem();
    }

    public JFrame getPredecesor() {
        return predecesor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        postulantData = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        topic = new javax.swing.JComboBox<>();
        level = new javax.swing.JSpinner();
        remove = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        listSkills = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        back = new javax.swing.JButton();
        go = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Entrevistas");
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Alta postulante");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(140, 10, 170, 22);

        postulantData.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        postulantData.setText("Postulante info");
        jPanel1.add(postulantData);
        postulantData.setBounds(140, 40, 110, 15);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel3.setText("Experiencia:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 160, 82, 20);

        jPanel1.add(topic);
        topic.setBounds(140, 70, 250, 23);

        level.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        level.setOpaque(true);
        jPanel1.add(level);
        level.setBounds(140, 100, 120, 23);

        remove.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        remove.setText("Eliminar");
        remove.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });
        jPanel1.add(remove);
        remove.setBounds(20, 210, 100, 21);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(30, 140, 370, 20);

        listSkills.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(listSkills);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(140, 160, 250, 80);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Nivel:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 100, 110, 20);

        add.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        add.setText("Agregar");
        add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add);
        add.setBounds(290, 100, 100, 21);

        back.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        back.setText("Atrás");
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back);
        back.setBounds(290, 300, 100, 21);

        go.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        go.setText("Registrar");
        go.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goActionPerformed(evt);
            }
        });
        jPanel1.add(go);
        go.setBounds(20, 300, 100, 21);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Tema:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 70, 110, 15);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Postulante:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 40, 110, 15);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 410, 360);

        setSize(new java.awt.Dimension(431, 397));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        JFrame ventanaActual = (JFrame) SwingUtilities.getWindowAncestor((Component) evt.getSource());
        ventanaActual.dispose();
        this.getPredecesor().setVisible(true);

    }//GEN-LAST:event_backActionPerformed

    private void goActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goActionPerformed
        // TODO add your handling code here:
        if (model.elementAt(0).toString() != "No hay experiencia.") {

            if (!this.system.addPostulant(this.postulant)) {
                JOptionPane.showMessageDialog(null, "No se pudo crear al postulante, ya existe.", "Error", JOptionPane.ERROR_MESSAGE);

            } else {

                //this.getSystem().resetPostulantMemory();
                JOptionPane.showMessageDialog(null, "El postulante se creo de manera exitosa!", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                JFrame ventanaActual = (JFrame) SwingUtilities.getWindowAncestor((Component) evt.getSource());
                ventanaActual.dispose();
                this.getPredecesor().dispose();

                Postulant postulantNew = new Postulant();
                AddPostulant newWindow = new AddPostulant(this.getSystem(), postulantNew);
                newWindow.setVisible(true);

            }
        } else {
            JOptionPane.showMessageDialog(null, "No se pudo crear al postulante, no se agrego experiencia.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_goActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        if (Integer.parseInt(level.getValue().toString()) >= 1 && Integer.parseInt(level.getValue().toString()) <= 10) {
            this.postulant.addSkills((Topic) topic.getSelectedItem(), Integer.parseInt(level.getValue().toString()));

            this.setListItem();
            this.setTopicCombo();
        } else {
            JOptionPane.showMessageDialog(null, "El nivel del tema debe estar entre 1 y 10.", "Error", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_addActionPerformed

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
        // TODO add your handling code here:
        if (!listSkills.isSelectionEmpty()) {
            Topic tSelected = this.getSystem().getTopicByName(listSkills.getSelectedValue().substring(0, listSkills.getSelectedValue().indexOf("(")));
            this.postulant.removeSkills(tSelected);

            this.setListItem();
            this.setTopicCombo();

//System.out.println(this.getSystem().getPostulantMemory().toString());
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar experiencia a eliminar.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_removeActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton back;
    private javax.swing.JButton go;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner level;
    private javax.swing.JList<String> listSkills;
    private javax.swing.JLabel postulantData;
    private javax.swing.JButton remove;
    private javax.swing.JComboBox<Topic> topic;
    // End of variables declaration//GEN-END:variables

    private void setTopicCombo() {
        topic.removeAllItems();
        ArrayList<Topic> topicList = getTopicsNotInMemory();
        for (Topic t : topicList) {
            topic.addItem(t);
        }
        int count = 0;
        for (int i = 0; i < topic.getComponentCount(); i++) {
            if (topic.getItemAt(i) != null) {
                count++;
            }
        }
        //System.out.println("TCount:"+topic.getComponentCount());
        if (count == 0) {
            topic.setEnabled(false);
            level.setEnabled(false);
            add.setEnabled(false);
            topic.addItem(new Topic("No hay temas registrados.", ""));
        } else {
            level.setEnabled(true);
            topic.setEnabled(true);
            add.setEnabled(true);
        }
    }

    private void setListItem() {
        model.removeAllElements();
        for (Map.Entry<Topic, Integer> entry : this.postulant.getSkills().entrySet()) {

            model.addElement(entry.getKey() + "(" + entry.getValue() + ")");
        }
        if (model.isEmpty()) {
            remove.setEnabled(false);
            listSkills.setEnabled(false);
            model.addElement("No hay experiencia.");
        } else {
            remove.setEnabled(true);
            listSkills.setEnabled(true);
        }
    }

    public SystemClass getSystem() {
        return system;
    }

    public ArrayList<Topic> getTopicsNotInMemory() {
        ArrayList<Topic> result = new ArrayList<Topic>();

        for (Topic t : this.system.getTopics()) {
            if (!this.postulant.getSkills().containsKey(t)) {
                result.add(t);
            }
        }

        return result;
    }

}
