/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import domain.Postulant;
import domain.SystemClass;
import java.awt.Component;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author bacosta
 */
public class AddPostulant extends javax.swing.JFrame {

    private SystemClass system;
    /**
     * Creates new form AddPostulant
     */
    public AddPostulant(SystemClass sys) {
        system = sys;
        initComponents();
        jobModalityR.setSelected(true);
        this.getSystem().setPostulantMemory(new Postulant());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jobModalityGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jobModalityH = new javax.swing.JRadioButton();
        jobModalityR = new javax.swing.JRadioButton();
        jobModalityP = new javax.swing.JRadioButton();
        go = new javax.swing.JButton();
        back = new javax.swing.JButton();
        name = new javax.swing.JTextField();
        linkedin = new javax.swing.JTextField();
        mail = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        document = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Entrevistas");
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setText("Alta postulante");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(150, 10, 105, 30);

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel2.setText("Teléfono:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 220, 80, 18);

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel3.setText("Nombre:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 70, 80, 18);

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel4.setText("Cédula:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 120, 80, 18);

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel5.setText("Formato:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 370, 120, 18);

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel6.setText("Dirección:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 170, 90, 18);

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel7.setText("Mail:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 270, 80, 18);

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel8.setText("Linkedin:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 320, 80, 18);

        jobModalityGroup.add(jobModalityH);
        jobModalityH.setText("Hybrido");
        jobModalityH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jobModalityHActionPerformed(evt);
            }
        });
        jPanel1.add(jobModalityH);
        jobModalityH.setBounds(310, 370, 110, 21);

        jobModalityGroup.add(jobModalityR);
        jobModalityR.setText("Remoto");
        jobModalityR.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jobModalityR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jobModalityRActionPerformed(evt);
            }
        });
        jPanel1.add(jobModalityR);
        jobModalityR.setBounds(100, 370, 100, 21);

        jobModalityGroup.add(jobModalityP);
        jobModalityP.setText("Presencial");
        jobModalityP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jobModalityPActionPerformed(evt);
            }
        });
        jPanel1.add(jobModalityP);
        jobModalityP.setBounds(200, 370, 110, 21);

        go.setText("Siguiente");
        go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goActionPerformed(evt);
            }
        });
        jPanel1.add(go);
        go.setBounds(20, 450, 120, 23);

        back.setText("Cancelar");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back);
        back.setBounds(270, 450, 120, 23);
        jPanel1.add(name);
        name.setBounds(100, 70, 280, 22);
        jPanel1.add(linkedin);
        linkedin.setBounds(100, 320, 280, 22);
        jPanel1.add(mail);
        mail.setBounds(100, 270, 280, 22);
        jPanel1.add(phone);
        phone.setBounds(100, 220, 280, 22);
        jPanel1.add(address);
        address.setBounds(100, 170, 280, 22);
        jPanel1.add(document);
        document.setBounds(100, 120, 280, 22);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-2, 4, 430, 490);

        setSize(new java.awt.Dimension(431, 521));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jobModalityHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jobModalityHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jobModalityHActionPerformed

    private void jobModalityRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jobModalityRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jobModalityRActionPerformed

    private void jobModalityPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jobModalityPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jobModalityPActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
         JFrame ventanaActual = (JFrame) SwingUtilities.getWindowAncestor((Component) evt.getSource());
         ventanaActual.dispose();
        // system.getMenuReference().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void goActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goActionPerformed
        if(name.getText().isBlank() || document.getText().isBlank() || address.getText().isBlank() ||
           mail.getText().isBlank() || phone.getText().isBlank()    || linkedin.getText().isBlank()){
                     JOptionPane.showMessageDialog(null, "Debe indicar todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);

        }else{
            
            
            
   
            this.getSystem().getPostulantMemory().setAddress(address.getText());
            this.getSystem().getPostulantMemory().setContact(phone.getText());
            this.getSystem().getPostulantMemory().setDocument(document.getText());
            this.getSystem().getPostulantMemory().setEmail(mail.getText());
            if (jobModalityR.isSelected()){
                this.getSystem().getPostulantMemory().setJobModality('R');
            }
            if (jobModalityP.isSelected()){
                this.getSystem().getPostulantMemory().setJobModality('P');
            }
            if (jobModalityH.isSelected()){
                this.getSystem().getPostulantMemory().setJobModality('H');
            }
            this.getSystem().getPostulantMemory().setLinkedin(linkedin.getText());
            this.getSystem().getPostulantMemory().setName(name.getText());
            
            
            JFrame ventanaActual = (JFrame) SwingUtilities.getWindowAncestor((Component) evt.getSource());
            
            
            AddPostulantSkills window = new AddPostulantSkills(this.getSystem(), ventanaActual);
            window.setVisible(true);
            this.setVisible(false);
            
        }
        
        
    }//GEN-LAST:event_goActionPerformed
    
    private void setFieldsFromMemory(){
        if(!this.getSystem().getPostulantMemory().getName().isBlank()){
        name.setText(this.getSystem().getPostulantMemory().getName());
        document.setText(this.getSystem().getPostulantMemory().getDocument());
        address.setText(this.getSystem().getPostulantMemory().getAddress());
        phone.setText(this.getSystem().getPostulantMemory().getContact());
        mail.setText(this.getSystem().getPostulantMemory().getEmail());
        linkedin.setText(this.getSystem().getPostulantMemory().getLinkedin());
        if(this.getSystem().getPostulantMemory().getJobModality()=='P'){
            jobModalityP.setSelected(true);
            jobModalityR.setSelected(false);
            jobModalityH.setSelected(false);
        }
        if(this.getSystem().getPostulantMemory().getJobModality()=='R'){
            jobModalityP.setSelected(false);
            jobModalityR.setSelected(true);
            jobModalityH.setSelected(false);
        }
        if(this.getSystem().getPostulantMemory().getJobModality()=='H'){
            jobModalityP.setSelected(false);
            jobModalityR.setSelected(false);
            jobModalityH.setSelected(true);
        }
        }
    
    
    }
    
    public SystemClass getSystem() {
        return system;
    }

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JButton back;
    private javax.swing.JTextField document;
    private javax.swing.JButton go;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.ButtonGroup jobModalityGroup;
    private javax.swing.JRadioButton jobModalityH;
    private javax.swing.JRadioButton jobModalityP;
    private javax.swing.JRadioButton jobModalityR;
    private javax.swing.JTextField linkedin;
    private javax.swing.JTextField mail;
    private javax.swing.JTextField name;
    private javax.swing.JTextField phone;
    // End of variables declaration//GEN-END:variables
}
