/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import domain.Position;
import domain.Postulant;
import domain.SystemClass;
import java.util.ArrayList;
import java.util.Observable;
import java.util.Observer;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author bacosta
 */
public class QueryPosition extends javax.swing.JFrame implements Observer {
  DefaultListModel modelPosition = new DefaultListModel();
  DefaultListModel modelPostulant = new DefaultListModel();
  private SystemClass system;
  
  /**
     * Creates new form QuerryPosition
     */
    public QueryPosition(SystemClass sys) {
        system = sys;
        initComponents();
        system.addObserver(this);
        positions.setModel(modelPosition);
        postulants.setModel(modelPostulant);
        setPositionList();
        setPostulantList();
    }
    public void update(Observable o,Object ob){
        
       setPositionList();
       setPostulantList();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        positions = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        level = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        postulants = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setText("Consulta por posicion");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(120, 40, 170, 18);

        jLabel2.setText("Nivel:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 240, 90, 20);

        positions.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                positionsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(positions);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 90, 350, 140);

        jLabel3.setText("Puestos:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 70, 90, 17);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(30, 270, 350, 10);

        level.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        level.setOpaque(true);
        jPanel1.add(level);
        level.setBounds(110, 240, 110, 23);

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(30, 460, 120, 23);

        jLabel4.setText("Postulantes:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 280, 90, 17);

        postulants.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(postulants);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(30, 300, 350, 140);

        jButton2.setText("Consultar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(258, 240, 120, 23);

        jButton3.setText("Exportar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(260, 460, 120, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 410, 510);

        setSize(new java.awt.Dimension(410, 533));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         if(Integer.parseInt(level.getValue().toString())>=1 && Integer.parseInt(level.getValue().toString())<=10){
            setPostulantList();
        }else{
         JOptionPane.showMessageDialog(null, "El nivel del tema debe estar entre 1 y 10.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void positionsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_positionsValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_positionsValueChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (!positions.isSelectionEmpty()){
        ArrayList<Postulant> arrayList = new ArrayList<Postulant>();
        int size = modelPostulant.getSize();
        for (int i = 0; i < size; i++) {
            Postulant item = (Postulant) modelPostulant.getElementAt(i);
            arrayList.add(item);
        }
        
        this.system.exportPositionQuery(positions.getSelectedValue(), arrayList);
        }else{
              JOptionPane.showMessageDialog(null, "Debe de seleccionar la posicion para poder exportar.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    private void setPositionList(){
        modelPosition.clear();
        for (Position p : this.system.getPositions()) {
            modelPosition.addElement(p);
        }
    }
    private void setPostulantList(){
        
        if(positions.isSelectionEmpty()){
            JOptionPane.showMessageDialog(null, "Debe seleccionar la posicion a consultar", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            modelPostulant.clear();
            for (Postulant e : this.system.getPostulantsRiseAllTopicLevel(positions.getSelectedValue(), (Integer)level.getValue())) {
                modelPostulant.addElement(e);
            }
            if(modelPostulant.isEmpty()){
                jButton3.setEnabled(false);
                modelPostulant.addElement(new Postulant("No hay resultados para su busqueda"));
            }else{
                jButton3.setEnabled(true);
            }
            
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner level;
    private javax.swing.JList<Position> positions;
    private javax.swing.JList<Postulant> postulants;
    // End of variables declaration//GEN-END:variables
}
