/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import domain.SystemClass;

/**
 *
 * @author bacosta
 */
public class RemovePosultant extends javax.swing.JFrame {
    private SystemClass system;
    /**
     * Creates new form RemovePosultant
     */
    public RemovePosultant(SystemClass sys) {
        system = sys;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        go = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        mail = new javax.swing.JLabel();
        document = new javax.swing.JLabel();
        contact = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setText("Baja postulante");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(150, 20, 106, 18);

        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 60, 130, 270);

        go.setText("Eliminar");
        jPanel1.add(go);
        go.setBounds(240, 300, 76, 23);

        back.setText("Volver");
        jPanel1.add(back);
        back.setBounds(160, 370, 78, 23);

        jLabel2.setText("Direccion:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(160, 220, 60, 17);

        jLabel3.setText("Correo:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(160, 130, 60, 17);

        jLabel4.setText("Cédula:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(160, 160, 60, 17);

        jLabel5.setText("Nombre:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(160, 100, 60, 17);

        jLabel6.setText("Teléfono:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(160, 190, 60, 17);
        jPanel1.add(address);
        address.setBounds(230, 220, 140, 0);
        jPanel1.add(name);
        name.setBounds(230, 100, 140, 0);
        jPanel1.add(mail);
        mail.setBounds(230, 130, 140, 0);
        jPanel1.add(document);
        document.setBounds(230, 160, 140, 0);
        jPanel1.add(contact);
        contact.setBounds(230, 190, 140, 0);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 430);

        setSize(new java.awt.Dimension(400, 455));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address;
    private javax.swing.JButton back;
    private javax.swing.JLabel contact;
    private javax.swing.JLabel document;
    private javax.swing.JButton go;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mail;
    private javax.swing.JLabel name;
    // End of variables declaration//GEN-END:variables
}
