/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import domain.Postulant;
import domain.SystemClass;
import java.awt.Component;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.Observable;
import java.util.Observer;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author bacosta
 */
public class RemovePostulant extends javax.swing.JFrame implements Observer{
    private SystemClass system;
    DefaultListModel model = new DefaultListModel();
    

    /**
     * Creates new form RemovePosultant
     */
    public RemovePostulant(SystemClass sys) {
        system = sys;
        system.addObserver(this);
        initComponents();
        postulantList.setModel(model);
        setList();
        setData();
        //system.addPropertyChangeLisener(this);
    }
    
    
    public void update(Observable o,Object ob){
        
        setList();
        setData();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        go = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        mail = new javax.swing.JLabel();
        document = new javax.swing.JLabel();
        contact = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        postulantList = new javax.swing.JList<>();
        name_info = new javax.swing.JLabel();
        address_info = new javax.swing.JLabel();
        mail_info = new javax.swing.JLabel();
        document_info = new javax.swing.JLabel();
        number_info = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setText("Baja postulante");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(180, 20, 106, 18);

        go.setText("Eliminar");
        go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goActionPerformed(evt);
            }
        });
        jPanel1.add(go);
        go.setBounds(300, 310, 90, 23);

        back.setText("Cancelar");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back);
        back.setBounds(180, 440, 100, 23);

        jLabel2.setText("Direccion:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(210, 220, 90, 17);

        jLabel3.setText("Correo:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(210, 130, 80, 17);

        jLabel4.setText("Cédula:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(210, 160, 80, 17);

        jLabel5.setText("Nombre:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(210, 100, 90, 17);

        jLabel6.setText("Teléfono:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(210, 190, 90, 17);
        jPanel1.add(address);
        address.setBounds(230, 220, 140, 0);
        jPanel1.add(name);
        name.setBounds(230, 100, 140, 0);
        jPanel1.add(mail);
        mail.setBounds(230, 130, 140, 0);
        jPanel1.add(document);
        document.setBounds(230, 160, 140, 0);
        jPanel1.add(contact);
        contact.setBounds(230, 190, 140, 0);

        postulantList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        postulantList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                postulantListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(postulantList);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 50, 190, 300);

        name_info.setText("Value");
        jPanel1.add(name_info);
        name_info.setBounds(280, 100, 160, 17);

        address_info.setText("Value");
        jPanel1.add(address_info);
        address_info.setBounds(280, 220, 170, 17);

        mail_info.setText("Value");
        jPanel1.add(mail_info);
        mail_info.setBounds(280, 130, 170, 17);

        document_info.setText("Value");
        jPanel1.add(document_info);
        document_info.setBounds(280, 160, 170, 17);

        number_info.setText("Value");
        jPanel1.add(number_info);
        number_info.setBounds(280, 190, 170, 17);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 460, 520);

        setSize(new java.awt.Dimension(459, 544));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        
        JFrame ventanaActual = (JFrame) SwingUtilities.getWindowAncestor((Component) evt.getSource());
            ventanaActual.dispose();
            //system.getMenuReference().setVisible(true);
            
    }//GEN-LAST:event_backActionPerformed

    private void postulantListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_postulantListValueChanged
        // TODO add your handling code here:
        setData();
       
        
    }//GEN-LAST:event_postulantListValueChanged

    private void goActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goActionPerformed
        // TODO add your handling code here:
        
        this.getSystem().removePostulant(postulantList.getSelectedValue());
        JOptionPane.showMessageDialog(null, "El postulante y su informacion fueron eliminados.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        //setList();
        //setData();
    }//GEN-LAST:event_goActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
       // this.getSystem().removePropertyChangeLisener(this);
    }//GEN-LAST:event_formWindowClosed

    private void setList(){
        model.clear();
        for (Postulant p : this.getSystem().getPostulants()) {
            model.addElement(p);
        }
        
    
        if (model.isEmpty()){
            go.setEnabled(false);
            model.addElement(new Postulant("No hay postulantes."));
        }else{
            go.setEnabled(true);
        }
    }

    public SystemClass getSystem() {
        return system;
    }
    private void setData(){
        if(!model.isEmpty() && postulantList.getSelectedValue()!=null){
            name_info.setText(postulantList.getSelectedValue().getName());
            mail_info.setText(postulantList.getSelectedValue().getEmail());
            document_info.setText(postulantList.getSelectedValue().getDocument());
            number_info.setText(postulantList.getSelectedValue().getContact());
            address_info.setText(postulantList.getSelectedValue().getAddress());
        }else{
            name_info.setText("");
            mail_info.setText("");
            document_info.setText("");
            number_info.setText("");
            address_info.setText("");
        }
    }
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address;
    private javax.swing.JLabel address_info;
    private javax.swing.JButton back;
    private javax.swing.JLabel contact;
    private javax.swing.JLabel document;
    private javax.swing.JLabel document_info;
    private javax.swing.JButton go;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mail;
    private javax.swing.JLabel mail_info;
    private javax.swing.JLabel name;
    private javax.swing.JLabel name_info;
    private javax.swing.JLabel number_info;
    private javax.swing.JList<Postulant> postulantList;
    // End of variables declaration//GEN-END:variables
}
